### ISSUE TITLE
How did you generate the Ids

### ISSUE THREAD

**Issue by Newmanater** [SuperNar3k/foundry#1]
Hi! 

Wondering if you could help me, I'm trying to do something simpler with some content I have created, and I'm wondering how you generated the Ids?

Thanks

**Comment by SuperNar3k** [comment]
Sorry this is so late @Newmanater  but i didn't get an email or any notification that you made this issue. For questions like these, it's best to just message me on Discord. Best way is to just drag-and-drop the item you're trying to show right into the paragraph.
